export const ESTAT_API_ERROR_TITLE = "e-Stat API データ取得エラー";
export const ESTAT_API_ERROR_MESSAGE = "APIキーの確認とネットワーク接続を確認してください。";
export const POPULATION_DATA_TITLE = "首都圏人口データ";
export const POPULATION_DATA_ERROR_MESSAGE = "e-Stat APIからデータを取得できませんでした。";
export const NO_DATA_SYMBOL = "-";
export const GOLD_GROUP_CLASS = "goldGroup";
export const SILVER_GROUP_CLASS = "silverGroup";
export const BRONZE_GROUP_CLASS = "bronzeGroup";
export const TABLE_TITLE = "首都圏人口データ（友好度グループ別色分け）";
export const DATA_COUNT_LABEL = "データ件数: ";
export const GROUP_COUNT_LABEL = "件 | グループ数: ";
export const GROUP_COUNT_UNIT = "つ";
export const TOTAL_SCORE_LABEL = "友好度合計スコア: ";
export const YEAR_HEADER = "西暦";
export const YEAR_UNIT = "年";
export const FOOTER_TEXT = "データ提供: e-Stat (政府統計の総合窓口) | 色分け: 友好度最適化グループ";
export const POPULATION_TABLE_ERROR_BOUNDARY_MESSAGE =
  "An error occurred while displaying the population table.";
export const LOADING_MESSAGE = "データを読み込み中...";
